### ISSUE TITLE
Embed text box undistinguishable 

### ISSUE THREAD

**Issue by atutr001** [slow/dark-discord#2]
![image](https://user-images.githubusercontent.com/75003853/133511710-181bee7d-9852-47c2-be6c-729d4058a7e6.png)
![image](https://user-images.githubusercontent.com/75003853/133511716-6880c499-2191-4c0a-8fd8-deb7e56b9668.png)
As you can see the "inactive" text box is in an embed and it's impossible to tell in the theme, it'd be nice if you cand give it some colour or definition.

**Comment by slow** [comment]
That's pure black, i don't think i can do much more than that.
